### ISSUE TITLE
Extra POST request even if no data is entered in form

### ISSUE THREAD

**Issue by lokeshgarg92** [digitalgreenorg/dg#578]
#571 
Add Video Quality Review form
click on "Save and Add Another" without entering any data in any field
There will be few warning to be addressed, Address them and click on "Save and Add another"
It will send a POST request and then will show error for "Missing fields"
Can this be handled without POST request ?

**Comment by sainivikas** [comment]
This was due to total score and video grade. When there were no answer for questions then it was sending packet to server but server returned packet with error because total score and video grade are mandatory on backend. Now all questions are mandatory, this ensures that there will be some entry in both of total score and video grade.
